---
- name: create repos destinattion directory
  ansible.builtin.file:
    path: "~/repos/mck-internal"
    state: directory

- name: clone repos
  ansible.builtin.git:
    repo: "org-62409820@github.com:{{ item }}.git"
    dest: "~/repos/{{ item | lower }}/"
    update: yes
  loop:
    - "geordan/dotfiles"
    - "geordan/mac-dev-playbook"
    - "geordan/wiki"
    - "McK-Internal/matter-compliance-matter-iac"
    - "McK-Internal/matter-compliance-matter-workflow"
    - "McK-Internal/matter-compliance-pipeline-services"
    - "McK-Internal/matter-compliance-regression-framework"
    - "McK-Internal/matter-compliance-snitch-cli"
    - "McK-Internal/matter-compliance-snitch-core"
    - "McK-Internal/matter-compliance-snitch-rules"
    - "McK-Internal/matter-compliance-snitch-types"
    - "McK-Internal/matter-compliance-snitch-utils"
    - "McK-Private/matter-compliance-bc-demo-aws"
    - "reactorworks/snitch2"
    - "reactorworks/snitch-docs-website"
